### ISSUE TITLE
Cannot Compile on Python3.9 Android ARM64 Termux

### ISSUE THREAD

**Issue by defencedog** [pyequion/pyequion2#3]
I have installed a near complete python stack on my Android including popular chemical libraries like CoolProp, Cantera which are fully functional in my jupyter notebooks.
My libraries versions

> Cython               0.29.21
> setuptools           58.1.0
> scipy                1.6.3
> numpy                1.20.3

While installing through pip (git version), following error occurs

```
rocessing /data/data/com.termux/files/home/pyequion2
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [228 lines of output]
      Collecting setuptools>=42
        Using cached setuptools-65.3.0-py3-none-any.whl (1.2 MB)
      Collecting Cython>=0.15.1
        Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
      Collecting numpy>=1.10
        Using cached numpy-1.23.3.tar.gz (10.7 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: numpy
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [202 lines of output]
            Running from numpy source directory.
            setup.py:86: DeprecationWarning:

              `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
              of the deprecation of `distutils` itself. It will be removed for
              Python >= 3.12. For older Python versions it will remain present.
              It is recommended to use `setuptools < 60.0` for those Python versions.
              For more details, see:
                https://numpy.org/devdocs/reference/distutils_status_migration.html


              import numpy.distutils.command.sdist
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_common.pyx
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/mtrand.pyx
            Cythonizing sources
            INFO: blas_opt_info:
            INFO: blas_armpl_info:
            INFO: customize UnixCCompiler
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blas_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blis_info:
            INFO:   libraries blis not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_info:
            INFO: C compiler: aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating /data/data/com.termux/files/usr/tmp/tmprg6neymz/data
            creating /data/data/com.termux/files/usr/tmp/tmprg6neymz/data/data
            creating /data/data/com.termux/files/usr/tmp/tmprg6neymz/data/data/com.termux
            creating /data/data/com.termux/files/usr/tmp/tmprg6neymz/data/data/com.termux/files
            creating /data/data/com.termux/files/usr/tmp/tmprg6neymz/data/data/com.termux/files/usr
            creating /data/data/com.termux/files/usr/tmp/tmprg6neymz/data/data/com.termux/files/usr/tmp
            creating /data/data/com.termux/files/usr/tmp/tmprg6neymz/data/data/com.termux/files/usr/tmp/tmprg6neymz
            INFO: compile options: '-c'
            INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmprg6neymz/source.c
            INFO: aarch64-linux-android-clang /data/data/com.termux/files/usr/tmp/tmprg6neymz/data/data/com.termux/files/usr/tmp/tmprg6neymz/source.o -L/data/data/com.termux/files/usr/lib -lopenblas -o /data/data/com.termux/files/usr/tmp/tmprg6neymz/a.out
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            non-existing path in 'numpy/distutils': 'site.cfg'
            INFO: lapack_opt_info:
            INFO: lapack_armpl_info:
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: lapack_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_lapack_info:
            INFO: C compiler: aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/data
            creating /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/data/data
            creating /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/data/data/com.termux
            creating /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/data/data/com.termux/files
            creating /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/data/data/com.termux/files/usr
            creating /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/data/data/com.termux/files/usr/tmp
            creating /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/data/data/com.termux/files/usr/tmp/tmpjojkuiiu
            INFO: compile options: '-c'
            INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/source.c
            INFO: aarch64-linux-android-clang /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/data/data/com.termux/files/usr/tmp/tmpjojkuiiu/source.o -L/data/data/com.termux/files/usr/lib -lopenblas -o /data/data/com.termux/files/usr/tmp/tmpjojkuiiu/a.out
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            Warning: attempted relative import with no known parent package
            /data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            INFO: build_src
            INFO: building py_modules sources
            creating build
            creating build/src.linux-aarch64-3.9
            creating build/src.linux-aarch64-3.9/numpy
            creating build/src.linux-aarch64-3.9/numpy/distutils
            INFO: building library "npymath" sources
            WARN: Could not locate executable armflang
            WARN: Could not locate executable gfortran
            WARN: Could not locate executable f95
            WARN: Could not locate executable ifort
            WARN: Could not locate executable ifc
            WARN: Could not locate executable lf95
            WARN: Could not locate executable pgfortran
            WARN: Could not locate executable nvfortran
            WARN: Could not locate executable f90
            WARN: Could not locate executable f77
            WARN: Could not locate executable fort
            WARN: Could not locate executable efort
            WARN: Could not locate executable efc
            WARN: Could not locate executable g77
            WARN: Could not locate executable g95
            WARN: Could not locate executable pathf95
            WARN: Could not locate executable nagfor
            WARN: Could not locate executable frt
            WARN: don't know how to compile Fortran code on platform 'posix'
            creating build/src.linux-aarch64-3.9/numpy/core
            creating build/src.linux-aarch64-3.9/numpy/core/src
            creating build/src.linux-aarch64-3.9/numpy/core/src/npymath
            INFO: conv_template:> build/src.linux-aarch64-3.9/numpy/core/src/npymath/npy_math_internal.h
            INFO:   adding 'build/src.linux-aarch64-3.9/numpy/core/src/npymath' to include_dirs.
            INFO: conv_template:> build/src.linux-aarch64-3.9/numpy/core/src/npymath/ieee754.c
            INFO: conv_template:> build/src.linux-aarch64-3.9/numpy/core/src/npymath/npy_math_complex.c
            INFO: None - nothing done with h_files = ['build/src.linux-aarch64-3.9/numpy/core/src/npymath/npy_math_internal.h']
            INFO: building library "npyrandom" sources
            INFO: building extension "numpy.core._multiarray_tests" sources
            creating build/src.linux-aarch64-3.9/numpy/core/src/multiarray
            INFO: conv_template:> build/src.linux-aarch64-3.9/numpy/core/src/multiarray/_multiarray_tests.c
            INFO: building extension "numpy.core._multiarray_umath" sources
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
                main()
              File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-qd9wz6jq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-qd9wz6jq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
                self.run_setup()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-qd9wz6jq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
                super(_BuildMetaLegacyBackend,
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-qd9wz6jq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 494, in <module>
                setup_package()
              File "setup.py", line 486, in setup_package
                setup(**metadata)
              File "/data/data/com.termux/files/usr/tmp/pip-install-9m104c90/numpy_0de947bf681d4f19a814efad3b9cb55d/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-qd9wz6jq/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
                return distutils.core.setup(**attrs)
              File "/data/data/com.termux/files/usr/lib/python3.9/distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
                self.run_command(cmd)
              File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-qd9wz6jq/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/data/data/com.termux/files/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-9m104c90/numpy_0de947bf681d4f19a814efad3b9cb55d/numpy/distutils/command/build.py", line 62, in run
                old_build.run(self)
              File "/data/data/com.termux/files/usr/lib/python3.9/distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/data/data/com.termux/files/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-9m104c90/numpy_0de947bf681d4f19a814efad3b9cb55d/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/data/data/com.termux/files/usr/tmp/pip-install-9m104c90/numpy_0de947bf681d4f19a814efad3b9cb55d/numpy/distutils/command/build_src.py", line 161, in build_sources
                self.build_extension_sources(ext)
              File "/data/data/com.termux/files/usr/tmp/pip-install-9m104c90/numpy_0de947bf681d4f19a814efad3b9cb55d/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
                sources = self.generate_sources(sources, ext)
              File "/data/data/com.termux/files/usr/tmp/pip-install-9m104c90/numpy_0de947bf681d4f19a814efad3b9cb55d/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 513, in generate_config_h
                check_math_capabilities(config_cmd, ext, moredefs, mathlibs)
              File "numpy/core/setup.py", line 176, in check_math_capabilities
                raise SystemError("One of the required function to build numpy is not"
            SystemError: One of the required function to build numpy is not available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos', 'atan', 'fmod', 'modf', 'frexp', 'ldexp']).
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by BubaVV** [comment]
It seems that you hit discrepancy between setup.py and requirements.txt dependencies. Latter looks more valid, but also depends on recent pip version to install pyqt correctly. Pip 20.0.2 fails, but 22.3.1 works well

**Comment by defencedog** [comment]
@BubaVV I cannot run a GUI using python on termux. So I remove `pyqt5` line from `requirements.txt` also:
```
nano /data/data/com.termux/files/usr/lib/python3.9/site-packages/pyequion2/__init__.py
#from .interface import InterfaceSystem
#from .gui import run as rungui
```

After that I did got along with the installation.

**Comment by BubaVV** [comment]
> I cannot run a GUI using python on termux

Looks like good feature request to implement package options, like pyequion[gui]

**Comment by defencedog** [comment]
Yes, the previous release was non-GUI so no problem. But I can run some examples that do not require GUI. Can I request some more examples non-GUI based

**Comment by BubaVV** [comment]
@defencedog Created PR making GUI optional requirement. It should work in Termux environment
https://github.com/pyequion/pyequion2/pull/4

**Comment by defencedog** [comment]
Worked like charm

```
~/pyequion2 $ pip install .
Processing /data/data/com.termux/files/home/pyequion2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.21.4 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from pyequion2==0.0.6.3) (1.23.4)
Collecting auto-mix-prep>=0.2.0 (from pyequion2==0.0.6.3)
  Downloading auto-mix-prep-0.2.0.tar.gz (2.9 kB)
  Preparing metadata (setup.py) ... done
Collecting cloudpickle>=2.0.0 (from pyequion2==0.0.6.3)
  Downloading cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: commentjson>=0.9.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from pyequion2==0.0.6.3) (0.9.0)
Requirement already satisfied: matplotlib>=3.5.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from pyequion2==0.0.6.3) (3.6.0)
Requirement already satisfied: ordered-set>=4.0.2 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from pyequion2==0.0.6.3) (4.1.0)
Collecting periodictable>=1.6.0 (from pyequion2==0.0.6.3)
  Downloading periodictable-1.6.1-py2.py3-none-any.whl (752 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 752.5/752.5 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: scipy>=1.7.3 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from pyequion2==0.0.6.3) (1.8.0)
Collecting pydub (from auto-mix-prep>=0.2.0->pyequion2==0.0.6.3)
  Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Requirement already satisfied: lark-parser<0.8.0,>=0.7.1 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from commentjson>=0.9.0->pyequion2==0.0.6.3) (0.7.8)
Requirement already satisfied: contourpy>=1.0.1 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from matplotlib>=3.5.0->pyequion2==0.0.6.3) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from matplotlib>=3.5.0->pyequion2==0.0.6.3) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from matplotlib>=3.5.0->pyequion2==0.0.6.3) (4.37.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from matplotlib>=3.5.0->pyequion2==0.0.6.3) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from matplotlib>=3.5.0->pyequion2==0.0.6.3) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from matplotlib>=3.5.0->pyequion2==0.0.6.3) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from matplotlib>=3.5.0->pyequion2==0.0.6.3) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from matplotlib>=3.5.0->pyequion2==0.0.6.3) (2.8.2)
Requirement already satisfied: six>=1.5 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.5.0->pyequion2==0.0.6.3) (1.16.0)
Downloading cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Building wheels for collected packages: pyequion2, auto-mix-prep
  Building wheel for pyequion2 (pyproject.toml) ... done
  Created wheel for pyequion2: filename=pyequion2-0.0.6.3-py3-none-any.whl size=94792 sha256=3f995ae54bcc836073d577010ffd571ebc4e113fe3c11b686be4dc517b83ca41
  Stored in directory: /data/data/com.termux/files/usr/tmp/pip-ephem-wheel-cache-i80g2szi/wheels/76/92/06/505db0a50c9642f71f05d6f2964389fc5071019bbb65b70d92
  Building wheel for auto-mix-prep (setup.py) ... done
  Created wheel for auto-mix-prep: filename=auto_mix_prep-0.2.0-py3-none-any.whl size=3474 sha256=272c66f34c610e5cd25cad1f86e50ed3344bb2bdc139c5a7f8472614d66c52e3
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/7e/47/ec/0d009666e22721445062e1cab7f036f2f9f8b8b5d99714fcde
Successfully built pyequion2 auto-mix-prep
Installing collected packages: pydub, periodictable, cloudpickle, auto-mix-prep, pyequion2
Successfully installed auto-mix-prep-0.2.0 cloudpickle-3.0.0 periodictable-1.6.1 pydub-0.25.1 pyequion2-0.0.6.3
```
